### PR TITLE
Details popup window

### PR DESCRIPTION
**Pull request by massaillon**
For the 8th milestone of our Mobile and desktop portfolio we Implemented the below:

    - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
    - When the user clicks (or taps) the close (X) button, the popup disappears.

    - we implement popups for both mobile and desktop screen sizes:

for this project, we made use of the below 

    - Basic JavaScript syntax.
    - JavaScript to manipulate DOM elements.
    - JavaScript events.
    - We parsed a Figma design template 1 to create a UI.

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @massaillon,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no description in the PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ismailco** [comment]
@massaillon, I see that you made some changes don't forget to add a description to this PR 😄

Screenshot_20220519_194300

**Comment by massaillon** [comment]
> @massaillon, I see that you made some changes don't forget to add a description to this PR 😄
> 
> Screenshot_20220519_194300

@Ismailco Thank you, sir
I added the pull request description now

**Review by phelian23 — APPROVED** [review]
Hi @massaillon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
